#!/bin/csh
# $Header: /home/cjm/cvs/autoguider/scripts/autoguider_get_guide_frames,v 1.2 2006-04-13 15:54:08 cjm Exp $
set gaiadisp = 0
if ( $#args == 1 ) then
	if( $1 == "-gaiadisp" ) then
		set gaiadisp = 1
	else if( $1 == "-help" ) then
		echo "autoguider_get_guide_frames [-gaiadisp]"
		exit 1
	else 
		echo "Unknown argument: $1"
		exit 1
else
	echo "autoguider_get_guide_frames [-gaiadisp]"
	exit 1
endif
alias getfits_command "/icc/bin/autoguider/commandserver/test/i386-linux/test_getfits_command"
set hostname = "autoguider1"
set port = "1234"
set file_number = 0
set done = 0
while ( "${done}" == 0 )
	set date_string = `/bin/date +"%Y-%m-%dT%H:%M:%S"`
	set filename = "guide_${date_string}_${file_number}.fits"
	getfits_command -h ${hostname} -p ${port} -c "getfits guide" -f guide_${date_string}_${file_number}.fits
	@ file_number ++
	if( ${gaiadisp} == 1 ) then
		gaiadisp ${filename}
	endif
end
#
# $Log: not supported by cvs2svn $
# Revision 1.1  2006/04/13 15:25:07  cjm
# Initial revision
#
#
