#!/bin/csh
# $Header: /home/cjm/cvs/autoguider/scripts/autoguider_make_dark,v 1.1 2006-05-05 17:23:17 cjm Exp $
set gaiadisp = 0
set exposure_length = "1000"
set exposure_count = "3"
set output_filename = ""
if ( $#argv > 0 ) then
    set next_arg = ""
    foreach arg ( $argv )
	if( "$arg" == "-gaiadisp" ) then
		set gaiadisp = 1
	else if( "$arg" == "-exposure_length" ) then
		set next_arg = "exposure_length"
	else if( "$arg" == "-exposure_count" ) then
		set next_arg = "exposure_count"
	else if( "$arg" == "-help" ) then
		echo "autoguider_make_dark [-exposure_length <ms>][-exposure_count <n>] -output <FITS filename>"
		exit 1
	else if( "$arg" == "-output" ) then
		set next_arg = "output_filename"
	else
		if( "${next_arg}" == "exposure_length" ) then
		    set exposure_length = "${arg}"
		    set next_arg = ""
		else if( "${next_arg}" == "exposure_count" ) then
		    set exposure_count = "${arg}"
		    set next_arg = ""
		else if( "${next_arg}" == "output_filename" ) then
		    set output_filename = "${arg}"
		    set next_arg = ""
		else
		    echo "Unknown argument: $arg"
		    exit 1
		endif
        endif
    end
endif
if( "${output_filename}" == "" ) then
    echo "No output filename specified."
    exit 1
endif
set output_leaf = `echo "${output_filename}" | sed "s/\(.*\).fits/\1/"`
if ( -r /home/dev/bin/autoguider/commandserver/test/i386-linux/send_command ) then
    alias send_command "/home/dev/bin/autoguider/commandserver/test/i386-linux/send_command"
else if ( -r /icc/bin/autoguider/commandserver/test/i386-linux/send_command ) then
    alias send_command "/icc/bin/autoguider/commandserver/test/i386-linux/send_command"
else
    echo "Could not find send_command."
    exit 2
endif
if ( -r /home/dev/bin/autoguider/commandserver/test/i386-linux/test_getfits_command ) then
    alias getfits_command "/home/dev/bin/autoguider/commandserver/test/i386-linux/test_getfits_command"
else if ( -r /icc/bin/autoguider/commandserver/test/i386-linux/test_getfits_command ) then
    alias getfits_command "/icc/bin/autoguider/commandserver/test/i386-linux/test_getfits_command"
else
    echo "Could not find test_getfits_command."
    exit 2
endif
if ( -r /home/dev/bin/ccd/misc/i386-linux/fits_median ) then
    alias fits_median "/home/dev/bin/ccd/misc/i386-linux/fits_median"
else if ( -r /icc/bin/ccd/misc/i386-linux/fits_median ) then
    alias fits_median "/icc/bin/ccd/misc/i386-linux/fits_median"
else
    echo "Could not find fits_median."
    exit 2
endif
set hostname = "autoguider1"
set port = "1234"
set file_number = 0
set done = 0
set median_command_arguments = "-o ${output_filename}"
while ( "${done}" == 0 )
	set date_string = `/bin/date +"%Y-%m-%dT%H:%M:%S"`
	set filename = "${output_leaf}_${file_number}.fits"
	set expose_output = `send_command -h ${hostname} -p ${port} -c "expose ${exposure_length}"`
	echo "expose ${exposure_length} returned : ${expose_output}"
	getfits_command -h ${hostname} -p ${port} -c "getfits field raw" -f ${filename}
	@ file_number ++
	if( "${gaiadisp}" == "1" ) then
		gaiadisp ${filename}
	endif
	set median_command_arguments = " ${median_command_arguments} -i ${filename}"
	if( "${file_number}" == "${exposure_count}" ) then
	    set done = 1
	endif
end
echo "About to create median."
echo "fits_median ${median_command_arguments}"
fits_median ${median_command_arguments}
echo "Dark median ${output_filename} created."
if( "${gaiadisp}" == "1" ) then
    gaiadisp ${output_filename}
endif
#
# $Log: not supported by cvs2svn $
#
