#!/bin/csh
# $Header: /home/cjm/cvs/autoguider/scripts/autoguider_get_autoguider_commands,v 1.1 2023-08-08 09:24:27 cjm Exp $
# autoguider_get_autoguider_commands <log filename> [<log filename>...]
if( $#argv < 1) then
	echo "autoguider_get_autoguider_commands <log filename> [<log filename>...]"
	exit 1
endif
grep 'Command is autoguider' $*
